// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCollection(arg1, arg2) {
  return window['go']['restmate']['RestMate']['AddCollection'](arg1, arg2);
}

export function AddEnv(arg1) {
  return window['go']['restmate']['RestMate']['AddEnv'](arg1);
}

export function AddVar(arg1, arg2, arg3) {
  return window['go']['restmate']['RestMate']['AddVar'](arg1, arg2, arg3);
}

export function ChoseFile() {
  return window['go']['restmate']['RestMate']['ChoseFile']();
}

export function ClearAllCookies() {
  return window['go']['restmate']['RestMate']['ClearAllCookies']();
}

export function DeleteCollection(arg1) {
  return window['go']['restmate']['RestMate']['DeleteCollection'](arg1);
}

export function DeleteCookies(arg1) {
  return window['go']['restmate']['RestMate']['DeleteCookies'](arg1);
}

export function DeleteEnv(arg1) {
  return window['go']['restmate']['RestMate']['DeleteEnv'](arg1);
}

export function DeleteRequest(arg1, arg2) {
  return window['go']['restmate']['RestMate']['DeleteRequest'](arg1, arg2);
}

export function DeleteVar(arg1, arg2) {
  return window['go']['restmate']['RestMate']['DeleteVar'](arg1, arg2);
}

export function DuplicateEnv(arg1) {
  return window['go']['restmate']['RestMate']['DuplicateEnv'](arg1);
}

export function DuplicateRequest(arg1, arg2) {
  return window['go']['restmate']['RestMate']['DuplicateRequest'](arg1, arg2);
}

export function ExportCollection(arg1) {
  return window['go']['restmate']['RestMate']['ExportCollection'](arg1);
}

export function GetAllCookies() {
  return window['go']['restmate']['RestMate']['GetAllCookies']();
}

export function GetCollections() {
  return window['go']['restmate']['RestMate']['GetCollections']();
}

export function GetEnvs() {
  return window['go']['restmate']['RestMate']['GetEnvs']();
}

export function GetRequest(arg1, arg2) {
  return window['go']['restmate']['RestMate']['GetRequest'](arg1, arg2);
}

export function ImportCollection() {
  return window['go']['restmate']['RestMate']['ImportCollection']();
}

export function InitFile(arg1, arg2) {
  return window['go']['restmate']['RestMate']['InitFile'](arg1, arg2);
}

export function InitRestMateDbFile() {
  return window['go']['restmate']['RestMate']['InitRestMateDbFile']();
}

export function InvokeRequest(arg1) {
  return window['go']['restmate']['RestMate']['InvokeRequest'](arg1);
}

export function MoveRequest(arg1, arg2, arg3, arg4) {
  return window['go']['restmate']['RestMate']['MoveRequest'](arg1, arg2, arg3, arg4);
}

export function RenameCollection(arg1, arg2) {
  return window['go']['restmate']['RestMate']['RenameCollection'](arg1, arg2);
}

export function RenameEnv(arg1, arg2) {
  return window['go']['restmate']['RestMate']['RenameEnv'](arg1, arg2);
}

export function RenameRequest(arg1, arg2, arg3) {
  return window['go']['restmate']['RestMate']['RenameRequest'](arg1, arg2, arg3);
}

export function SelectEnv(arg1) {
  return window['go']['restmate']['RestMate']['SelectEnv'](arg1);
}

export function Startup(arg1) {
  return window['go']['restmate']['RestMate']['Startup'](arg1);
}

export function UpsertRequest(arg1) {
  return window['go']['restmate']['RestMate']['UpsertRequest'](arg1);
}
