// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {restmate} from '../models';
import {context} from '../models';

export function AddCollection(arg1:string,arg2:string):Promise<restmate.JSResp>;

export function AddEnv(arg1:string):Promise<restmate.JSResp>;

export function AddVar(arg1:string,arg2:string,arg3:string):Promise<restmate.JSResp>;

export function ChoseFile():Promise<restmate.JSResp>;

export function ClearAllCookies():Promise<restmate.JSResp>;

export function DeleteCollection(arg1:string):Promise<restmate.JSResp>;

export function DeleteCookies(arg1:string):Promise<restmate.JSResp>;

export function DeleteEnv(arg1:string):Promise<restmate.JSResp>;

export function DeleteRequest(arg1:string,arg2:string):Promise<restmate.JSResp>;

export function DeleteVar(arg1:string,arg2:string):Promise<restmate.JSResp>;

export function DuplicateEnv(arg1:string):Promise<restmate.JSResp>;

export function DuplicateRequest(arg1:string,arg2:string):Promise<restmate.JSResp>;

export function ExportCollection(arg1:string):Promise<restmate.JSResp>;

export function GetAllCookies():Promise<restmate.JSResp>;

export function GetCollections():Promise<restmate.JSResp>;

export function GetEnvs():Promise<restmate.JSResp>;

export function GetRequest(arg1:string,arg2:string):Promise<restmate.JSResp>;

export function ImportCollection():Promise<restmate.JSResp>;

export function InitFile(arg1:string,arg2:string):Promise<void>;

export function InitRestMateDbFile():Promise<void>;

export function InvokeRequest(arg1:restmate.Request):Promise<restmate.JSResp>;

export function MoveRequest(arg1:string,arg2:string,arg3:string,arg4:string):Promise<restmate.JSResp>;

export function RenameCollection(arg1:string,arg2:string):Promise<restmate.JSResp>;

export function RenameEnv(arg1:string,arg2:string):Promise<restmate.JSResp>;

export function RenameRequest(arg1:string,arg2:string,arg3:string):Promise<restmate.JSResp>;

export function SelectEnv(arg1:string):Promise<restmate.JSResp>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpsertRequest(arg1:restmate.Request):Promise<restmate.JSResp>;
