// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gorm} from '../models';
import {unwxapp} from '../models';
import {system} from '../models';
import {context} from '../models';

export function AutoDecompile(arg1:boolean):Promise<void>;

export function CheckDecompileStatus(arg1:string,arg2:string):Promise<string>;

export function ClearApplet():Promise<void>;

export function ClearDecompiled():Promise<void>;

export function Db():Promise<gorm.DB>;

export function Decompile(arg1:unwxapp.InfoToFront):Promise<void>;

export function ExtractSensitiveInfo(arg1:string,arg2:string):Promise<void>;

export function GetAllMiniApp():Promise<Array<unwxapp.InfoToFront>>;

export function GetAppPath():Promise<string>;

export function GetAppletPath():Promise<string>;

export function GetMatchedString(arg1:string,arg2:string):Promise<Array<string>>;

export function GetWechatRules():Promise<Array<string>>;

export function InitCheck():Promise<boolean>;

export function InitMianSha():Promise<system.Base>;

export function Log(arg1:string):Promise<system.Base>;

export function SaveWechatRules(arg1:Array<string>):Promise<void>;

export function Schema(arg1:Array<any>):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SetAppletPath(arg1:string):Promise<void>;

export function SetCtx(arg1:context.Context):Promise<void>;
