// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoDecompile(arg1) {
  return window['go']['unwxapp']['UnWxapp']['AutoDecompile'](arg1);
}

export function CheckDecompileStatus(arg1, arg2) {
  return window['go']['unwxapp']['UnWxapp']['CheckDecompileStatus'](arg1, arg2);
}

export function ClearApplet() {
  return window['go']['unwxapp']['UnWxapp']['ClearApplet']();
}

export function ClearDecompiled() {
  return window['go']['unwxapp']['UnWxapp']['ClearDecompiled']();
}

export function Db() {
  return window['go']['unwxapp']['UnWxapp']['Db']();
}

export function Decompile(arg1) {
  return window['go']['unwxapp']['UnWxapp']['Decompile'](arg1);
}

export function ExtractSensitiveInfo(arg1, arg2) {
  return window['go']['unwxapp']['UnWxapp']['ExtractSensitiveInfo'](arg1, arg2);
}

export function GetAllMiniApp() {
  return window['go']['unwxapp']['UnWxapp']['GetAllMiniApp']();
}

export function GetAppPath() {
  return window['go']['unwxapp']['UnWxapp']['GetAppPath']();
}

export function GetAppletPath() {
  return window['go']['unwxapp']['UnWxapp']['GetAppletPath']();
}

export function GetMatchedString(arg1, arg2) {
  return window['go']['unwxapp']['UnWxapp']['GetMatchedString'](arg1, arg2);
}

export function GetWechatRules() {
  return window['go']['unwxapp']['UnWxapp']['GetWechatRules']();
}

export function InitCheck() {
  return window['go']['unwxapp']['UnWxapp']['InitCheck']();
}

export function InitMianSha() {
  return window['go']['unwxapp']['UnWxapp']['InitMianSha']();
}

export function Log(arg1) {
  return window['go']['unwxapp']['UnWxapp']['Log'](arg1);
}

export function SaveWechatRules(arg1) {
  return window['go']['unwxapp']['UnWxapp']['SaveWechatRules'](arg1);
}

export function Schema(arg1) {
  return window['go']['unwxapp']['UnWxapp']['Schema'](arg1);
}

export function SelectDirectory() {
  return window['go']['unwxapp']['UnWxapp']['SelectDirectory']();
}

export function SetAppletPath(arg1) {
  return window['go']['unwxapp']['UnWxapp']['SetAppletPath'](arg1);
}

export function SetCtx(arg1) {
  return window['go']['unwxapp']['UnWxapp']['SetCtx'](arg1);
}
