// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowserOpenURL(arg1) {
  return window['go']['system']['System']['BrowserOpenURL'](arg1);
}

export function ClipboardGetText() {
  return window['go']['system']['System']['ClipboardGetText']();
}

export function ClipboardSetText(arg1) {
  return window['go']['system']['System']['ClipboardSetText'](arg1);
}

export function Db() {
  return window['go']['system']['System']['Db']();
}

export function ExitApp() {
  return window['go']['system']['System']['ExitApp']();
}

export function GetAppPath() {
  return window['go']['system']['System']['GetAppPath']();
}

export function GetAutoStart() {
  return window['go']['system']['System']['GetAutoStart']();
}

export function GetCPUUsage() {
  return window['go']['system']['System']['GetCPUUsage']();
}

export function GetConfigDir() {
  return window['go']['system']['System']['GetConfigDir']();
}

export function GetMemUsageSelf() {
  return window['go']['system']['System']['GetMemUsageSelf']();
}

export function GetMemUsageTotal() {
  return window['go']['system']['System']['GetMemUsageTotal']();
}

export function GetOpenChooseFilePath(arg1) {
  return window['go']['system']['System']['GetOpenChooseFilePath'](arg1);
}

export function GetOpenDir() {
  return window['go']['system']['System']['GetOpenDir']();
}

export function GetOpenFilePath() {
  return window['go']['system']['System']['GetOpenFilePath']();
}

export function GetOs() {
  return window['go']['system']['System']['GetOs']();
}

export function InitMianSha() {
  return window['go']['system']['System']['InitMianSha']();
}

export function Log(arg1) {
  return window['go']['system']['System']['Log'](arg1);
}

export function OpenConfigDir() {
  return window['go']['system']['System']['OpenConfigDir']();
}

export function OpenPath(arg1) {
  return window['go']['system']['System']['OpenPath'](arg1);
}

export function Schema(arg1) {
  return window['go']['system']['System']['Schema'](arg1);
}

export function SetAutoStart(arg1) {
  return window['go']['system']['System']['SetAutoStart'](arg1);
}

export function SetCtx(arg1) {
  return window['go']['system']['System']['SetCtx'](arg1);
}

export function ShellCMD(arg1, arg2, arg3, arg4) {
  return window['go']['system']['System']['ShellCMD'](arg1, arg2, arg3, arg4);
}
