// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gorm} from '../models';
import {system} from '../models';
import {context} from '../models';

export function BrowserOpenURL(arg1:string):Promise<void>;

export function ClipboardGetText():Promise<string>;

export function ClipboardSetText(arg1:string):Promise<void>;

export function Db():Promise<gorm.DB>;

export function ExitApp():Promise<void>;

export function GetAppPath():Promise<string>;

export function GetAutoStart():Promise<boolean>;

export function GetCPUUsage():Promise<number>;

export function GetConfigDir():Promise<string>;

export function GetMemUsageSelf():Promise<number>;

export function GetMemUsageTotal():Promise<number>;

export function GetOpenChooseFilePath(arg1:string):Promise<string>;

export function GetOpenDir():Promise<string>;

export function GetOpenFilePath():Promise<string>;

export function GetOs():Promise<string>;

export function InitMianSha():Promise<system.Base>;

export function Log(arg1:string):Promise<system.Base>;

export function OpenConfigDir():Promise<void>;

export function OpenPath(arg1:string):Promise<void>;

export function Schema(arg1:Array<any>):Promise<void>;

export function SetAutoStart(arg1:boolean):Promise<boolean>;

export function SetCtx(arg1:context.Context):Promise<void>;

export function ShellCMD(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;
