// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelExit() {
  return window['go']['system']['SystemTp']['CancelExit']();
}

export function ConfirmExit() {
  return window['go']['system']['SystemTp']['ConfirmExit']();
}

export function Db() {
  return window['go']['system']['SystemTp']['Db']();
}

export function GetAppPath() {
  return window['go']['system']['SystemTp']['GetAppPath']();
}

export function InitMianSha() {
  return window['go']['system']['SystemTp']['InitMianSha']();
}

export function Log(arg1) {
  return window['go']['system']['SystemTp']['Log'](arg1);
}

export function Schema(arg1) {
  return window['go']['system']['SystemTp']['Schema'](arg1);
}

export function SetCtx(arg1) {
  return window['go']['system']['SystemTp']['SetCtx'](arg1);
}

export function Startup(arg1, arg2) {
  return window['go']['system']['SystemTp']['Startup'](arg1, arg2);
}
