// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gorm} from '../models';
import {system} from '../models';
import {context} from '../models';

export function Db():Promise<gorm.DB>;

export function DownloadAndUpdate():Promise<system.DownloadResult>;

export function GetAppPath():Promise<string>;

export function GetLatestRelease():Promise<system.CheckResult>;

export function InitMianSha():Promise<system.Base>;

export function Log(arg1:string):Promise<system.Base>;

export function RestartApplication():Promise<void>;

export function Schema(arg1:Array<any>):Promise<void>;

export function SetCtx(arg1:context.Context):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
