// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Db() {
  return window['go']['system']['Update']['Db']();
}

export function DownloadAndUpdate() {
  return window['go']['system']['Update']['DownloadAndUpdate']();
}

export function GetAppPath() {
  return window['go']['system']['Update']['GetAppPath']();
}

export function GetLatestRelease() {
  return window['go']['system']['Update']['GetLatestRelease']();
}

export function InitMianSha() {
  return window['go']['system']['Update']['InitMianSha']();
}

export function Log(arg1) {
  return window['go']['system']['Update']['Log'](arg1);
}

export function RestartApplication() {
  return window['go']['system']['Update']['RestartApplication']();
}

export function Schema(arg1) {
  return window['go']['system']['Update']['Schema'](arg1);
}

export function SetCtx(arg1) {
  return window['go']['system']['Update']['SetCtx'](arg1);
}

export function Startup(arg1) {
  return window['go']['system']['Update']['Startup'](arg1);
}
