package model

import (
	"log"

	"gorm.io/gorm"
)

const TableNameAntivirus = "antivirus_list"

type Antivirus_list struct {
	ID           int    `json:"id"`
	Process_name string `json:"process_name"`
	Description  string `json:"description"`
}

func (*Antivirus_list) TableName() string {
	return TableNameAntivirus
}

func (s *Antivirus_list) Initialize(db *gorm.DB) {
	var count int64
	if err := db.Model(&Antivirus_list{}).Count(&count).Error; err != nil {
		log.Fatalf("Error counting records: %v", err)
	}

	if count == 0 {
		defaultSites := []Antivirus_list{
			{Process_name: "avgaurd.exe", Description: "avira antivir"},
			{Process_name: "cpf.exe", Description: "comodo"},
			{Process_name: "emet_agent.exe", Description: "emet"},
			{Process_name: "emet_service.exe", Description: "emet"},
			{Process_name: "avconsol.exe", Description: "mcafee"},
			{Process_name: "avsynmgr.exe", Description: "mcafee"},
			{Process_name: "cpd.exe", Description: "mcafee"},
			{Process_name: "firesvc.exe", Description: "mcafee"},
			{Process_name: "firetray.exe", Description: "mcafee"},
			{Process_name: "hipsvc.exe", Description: "mcafee"},
			{Process_name: "mcafeefire.exe", Description: "mcafee"},
			{Process_name: "mcscript.exe", Description: "mcafee"},
			{Process_name: "updaterui.exe", Description: "mcafee"},
			{Process_name: "cleanup.exe", Description: "mcafee"},
			{Process_name: "cmdagent.exe", Description: "Comodo Antivirus - 后台代理服务"},
			{Process_name: "frminst.exe", Description: "mcafee"},
			{Process_name: "mcscript_inuse.exe", Description: "mcafee"},
			{Process_name: "alogserv.exe", Description: "mcafee virusscan"},
			{Process_name: "_avp32.exe", Description: "卡巴斯基"},
			{Process_name: "_avpcc.exe", Description: "卡巴斯基"},
			{Process_name: "_avpm.exe", Description: "卡巴斯基"},
			{Process_name: "alertsvc.exe", Description: "norton antivirus"},
			{Process_name: "anti-trojan.exe", Description: "anti-trojan elite"},
			{Process_name: "arr.exe", Description: "application request route"},
			{Process_name: "atguard.exe", Description: "antivir"},
			{Process_name: "atwatch.exe", Description: "mustek"},
			{Process_name: "au.exe", Description: "nsis"},
			{Process_name: "aupdate.exe", Description: "symantec"},
			{Process_name: "autodown.exe", Description: "antivirus autoupdater"},
			{Process_name: "aavgapi.exe", Description: "avg"},
			{Process_name: "avgcc32.exe", Description: "avg"},
			{Process_name: "avgctrl.exe", Description: "avg"},
			{Process_name: "avgemc.exe", Description: "avg"},
			{Process_name: "avgrsx.exe", Description: "avg"},
			{Process_name: "avgserv.exe", Description: "avg"},
			{Process_name: "avgserv9.exe", Description: "avg"},
			{Process_name: "avgw.exe", Description: "avg"},
			{Process_name: "avkpop.exe", Description: "g data software ag"},
			{Process_name: "avkserv.exe", Description: "g data software ag"},
			{Process_name: "avkservice.exe", Description: "g data software ag"},
			{Process_name: "avkwctl9.exe", Description: "g data software ag"},
			{Process_name: "avltmain.exe", Description: "panda software aplication"},
			{Process_name: "avnt.exe", Description: "h+bedv datentechnik gmbh"},
			{Process_name: "avpdos32.exe", Description: "kaspersky antivirus"},
			{Process_name: "avpm.exe", Description: "kaspersky antivirus"},
			{Process_name: "avptc32.exe", Description: "kaspersky antivirus"},
			{Process_name: "avpupd.exe", Description: "kaspersky antivirus"},
			{Process_name: "avwin.exe", Description: "h+bedv"},
			{Process_name: "bargains.exe", Description: "exact advertising spyware"},
			{Process_name: "beagle.exe", Description: "avast"},
			{Process_name: "blackd.exe", Description: "blackice"},
			{Process_name: "blackice.exe", Description: "blackice"},
			{Process_name: "blink.exe", Description: "micromedia"},
			{Process_name: "blss.exe", Description: "cblaster"},
			{Process_name: "bootwarn.exe", Description: "symantec"},
			{Process_name: "bpc.exe", Description: "grokster"},
			{Process_name: "brasil.exe", Description: "exact advertising"},
			{Process_name: "ccevtmgr.exe", Description: "norton internet security"},
			{Process_name: "cdp.exe", Description: "cyberlink corp."},
			{Process_name: "cfd.exe", Description: "motive communications"},
			{Process_name: "cfgwiz.exe", Description: "norton antivirus"},
			{Process_name: "clean.exe", Description: "windows流氓软件清理大师"},
			{Process_name: "cleaner.exe", Description: "windows流氓软件清理大师"},
			{Process_name: "cleaner3.exe", Description: "windows流氓软件清理大师"},
			{Process_name: "cleanpc.exe", Description: "windows流氓软件清理大师"},
			{Process_name: "defalert.exe", Description: "symantec"},
			{Process_name: "defscangui.exe", Description: "symantec"},
			{Process_name: "defwatch.exe", Description: "norton antivirus"},
			{Process_name: "dpps2.exe", Description: "panicware"},
			{Process_name: "dssagent.exe", Description: "broderbund"},
			{Process_name: "emsw.exe", Description: "alset inc"},
			{Process_name: "ethereal.exe", Description: "rationalclearcase"},
			{Process_name: "fast.exe", Description: "fastusr"},
			{Process_name: "fch32.exe", Description: "f-secure"},
			{Process_name: "fih32.exe", Description: "f-secure"},
			{Process_name: "findviru.exe", Description: "f-secure"},
			{Process_name: "firewall.exe", Description: "ashampoosoftware"},
			{Process_name: "fnrb32.exe", Description: "f-secure"},
			{Process_name: "fp-win.exe", Description: "f-prot antivirus ondemand"},
			{Process_name: "fsaa.exe", Description: "f-secure"},
			{Process_name: "fsav.exe", Description: "f-secure"},
			{Process_name: "fsav32.exe", Description: "F-Secure Antivirus - 主杀毒进程"},
			{Process_name: "fsav530stbyb.exe", Description: "f-secure"},
			{Process_name: "fsav530wtbyb.exe", Description: "f-secure"},
			{Process_name: "fsav95.exe", Description: "f-secure"},
			{Process_name: "fsgk32.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "fsm32.exe", Description: "f-secure"},
			{Process_name: "fsma32.exe", Description: "F-Secure Management Agent"},
			{Process_name: "fsmb32.exe", Description: "f-secure"},
			{Process_name: "guard.exe", Description: "ewido"},
			{Process_name: "guarddog.exe", Description: "ewido"},
			{Process_name: "htpatch.exe", Description: "silicon integrated systems corporation"},
			{Process_name: "iamapp.exe", Description: "symantec"},
			{Process_name: "iamserv.exe", Description: "symantec"},
			{Process_name: "iamstats.exe", Description: "symantec"},
			{Process_name: "iedriver.exe", Description: "urlblaze.com"},
			{Process_name: "iface.exe", Description: "panda antivirus module"},
			{Process_name: "infus.exe", Description: "infus dialer"},
			{Process_name: "infwin.exe", Description: "msviewparasite"},
			{Process_name: "intdel.exe", Description: "inet delivery"},
			{Process_name: "keenvalue.exe", Description: "euniverse inc"},
			{Process_name: "launcher.exe", Description: "intercort systems"},
			{Process_name: "ldscan.exe", Description: "windows trojans inspector"},
			{Process_name: "luall.exe", Description: "symantec"},
			{Process_name: "luau.exe", Description: "symantec"},
			{Process_name: "lucomserver.exe", Description: "norton"},
			{Process_name: "mcagent.exe", Description: "mcafee"},
			{Process_name: "mcmnhdlr.exe", Description: "mcafee"},
			{Process_name: "mctool.exe", Description: "mcafee"},
			{Process_name: "mcupdate.exe", Description: "mcafee"},
			{Process_name: "mcvsrte.exe", Description: "mcafee"},
			{Process_name: "mcvsshld.exe", Description: "mcafee"},
			{Process_name: "mfin32.exe", Description: "myfreeinternetupdate"},
			{Process_name: "mfw2en.exe", Description: "myfreeinternetupdate"},
			{Process_name: "mfweng3.02d30.exe", Description: "myfreeinternetupdate"},
			{Process_name: "mgavrtcl.exe", Description: "mcafee"},
			{Process_name: "mgavrte.exe", Description: "mcafee"},
			{Process_name: "mghtml.exe", Description: "mcafee"},
			{Process_name: "mgui.exe", Description: "bullguard"},
			{Process_name: "mmod.exe", Description: "ezulainc"},
			{Process_name: "mostat.exe", Description: "wurldmediainc"},
			{Process_name: "mpfagent.exe", Description: "mcafee"},
			{Process_name: "mpfservice.exe", Description: "mcafee"},
			{Process_name: "mpftray.exe", Description: "mcafee"},
			{Process_name: "mscache.exe", Description: "integrated search technologies spyware"},
			{Process_name: "mscman.exe", Description: "odysseusmarketinginc"},
			{Process_name: "msmgt.exe", Description: "total velocity spyware"},
			{Process_name: "msvxd.exe", Description: "w32/datom-a"},
			{Process_name: "nav.exe", Description: "reuters limited"},
			{Process_name: "navapsvc.exe", Description: "norton antivirus"},
			{Process_name: "navapw32.exe", Description: "norton antivirus"},
			{Process_name: "navw32.exe", Description: "norton antivirus"},
			{Process_name: "ndd32.exe", Description: "诺顿磁盘医生"},
			{Process_name: "nisserv.exe", Description: "norton"},
			{Process_name: "nisum.exe", Description: "norton"},
			{Process_name: "nmain.exe", Description: "norton"},
			{Process_name: "nprotect.exe", Description: "symantec"},
			{Process_name: "npscheck.exe", Description: "norton"},
			{Process_name: "npssvc.exe", Description: "norton"},
			{Process_name: "outpostinstall.exe", Description: "outpost"},
			{Process_name: "patch.exe", Description: "趋势科技"},
			{Process_name: "pcscan.exe", Description: "趋势科技"},
			{Process_name: "persfw.exe", Description: "tiny personal firewall"},
			{Process_name: "pgmonitr.exe", Description: "promulgate spyware"},
			{Process_name: "pop3trap.exe", Description: "pc-cillin"},
			{Process_name: "poproxy.exe", Description: "nortonantivirus"},
			{Process_name: "powerscan.exe", Description: "integrated search technologies"},
			{Process_name: "prizesurfer.exe", Description: "prizesurfer"},
			{Process_name: "prmt.exe", Description: "opistat"},
			{Process_name: "prmvr.exe", Description: "adtomi"},
			{Process_name: "processmonitor.exe", Description: "sysinternals"},
			{Process_name: "protectx.exe", Description: "protectx"},
			{Process_name: "qconsole.exe", Description: "norton antivirus quarantine console"},
			{Process_name: "qserver.exe", Description: "norton internet security"},
			{Process_name: "rapapp.exe", Description: "blackice"},
			{Process_name: "rb32.exe", Description: "rapidblaster"},
			{Process_name: "rcsync.exe", Description: "prizesurfer"},
			{Process_name: "realmon.exe", Description: "realmon"},
			{Process_name: "rescue32.exe", Description: "卡巴斯基互联网安全套装"},
			{Process_name: "rtvscn95.exe", Description: "real-time virus scanner"},
			{Process_name: "rulaunch.exe", Description: "mcafee user interface"},
			{Process_name: "run32dll.exe", Description: "pal pc spy"},
			{Process_name: "safeweb.exe", Description: "psafe tecnologia"},
			{Process_name: "sbserv.exe", Description: "norton antivirus"},
			{Process_name: "sfc.exe", Description: "system file checker"},
			{Process_name: "sh.exe", Description: "mks toolkit for win3"},
			{Process_name: "showbehind.exe", Description: "microsmarts enterprise component"},
			{Process_name: "soap.exe", Description: "system soap pro"},
			{Process_name: "supporter5.exe", Description: "escorcher反病毒"},
			{Process_name: "symproxysvc.exe", Description: "symantec"},
			{Process_name: "symtray.exe", Description: "symantec"},
			{Process_name: "tbscan.exe", Description: "thunderbyte"},
			{Process_name: "tc.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "titanin.exe", Description: "titanhide"},
			{Process_name: "tvmd.exe", Description: "total velocity"},
			{Process_name: "tvtmd.exe", Description: "total velocity"},
			{Process_name: "vettray.exe", Description: "etrust"},
			{Process_name: "vpc32.exe", Description: "symantec"},
			{Process_name: "vpc42.exe", Description: "symantec"},
			{Process_name: "vshwin32.exe", Description: "mcafee"},
			{Process_name: "vsmain.exe", Description: "mcafee"},
			{Process_name: "vsstat.exe", Description: "mcafee"},
			{Process_name: "zapro.exe", Description: "zone alarm"},
			{Process_name: "zonealarm.exe", Description: "zone alarm"},
			{Process_name: "a2cmd.exe", Description: "emsisoft anti-malware"},
			{Process_name: "a2service.exe", Description: "a-squared free"},
			{Process_name: "a2free.exe", Description: "a-squared free"},
			{Process_name: "advchk.exe", Description: "norton antivirus"},
			{Process_name: "agb.exe", Description: "安天防线"},
			{Process_name: "ahprocmonserver.exe", Description: "安天防线"},
			{Process_name: "airdefense.exe", Description: "airdefense"},
			{Process_name: "avira.exe", Description: "Avira(小红伞)"},
			{Process_name: "amon.exe", Description: "tiny personal firewall"},
			{Process_name: "avz.exe", Description: "avz"},
			{Process_name: "apvxdwin.exe", Description: "熊猫卫士"},
			{Process_name: "ashmaisv.exe", Description: "alwil"},
			{Process_name: "ashserv.exe", Description: "avast anti-virus"},
			{Process_name: "ashsimpl.exe", Description: "avast!viruscleaner"},
			{Process_name: "ashwebsv.exe", Description: "avast"},
			{Process_name: "aswupdsv.exe", Description: "avast"},
			{Process_name: "aswscan.exe", Description: "avast"},
			{Process_name: "avciman.exe", Description: "熊猫卫士"},
			{Process_name: "avengine.exe", Description: "熊猫卫士"},
			{Process_name: "avesvc.exe", Description: "avira antivir security service"},
			{Process_name: "avgchsvx.exe", Description: "avg"},
			{Process_name: "avgcsrvx.exe", Description: "avg"},
			{Process_name: "avgnsx.exe", Description: "avg"},
			{Process_name: "avgfwsrv.exe", Description: "avg"},
			{Process_name: "avgntmgr.exe", Description: "avg"},
			{Process_name: "avgtray.exe", Description: "avg"},
			{Process_name: "avgupsvc.exe", Description: "avg"},
			{Process_name: "avinitnt.exe", Description: "command antivirus for nt server"},
			{Process_name: "avserver.exe", Description: "kerio mailserver"},
			{Process_name: "avsched32.exe", Description: "h+bedv"},
			{Process_name: "avwupsrv.exe", Description: "h+bedv"},
			{Process_name: "bdswitch.exe", Description: "bitdefender module"},
			{Process_name: "clamwin.exe", Description: "clamwin portable"},
			{Process_name: "cureit.exe", Description: "drweb cureit"},
			{Process_name: "drwadins.exe", Description: "dr.web"},
			{Process_name: "drweb.exe", Description: "dr.web"},
			{Process_name: "defenderdaemon.exe", Description: "shadowdefender"},
			{Process_name: "ewidoctrl.exe", Description: "ewido security suite"},
			{Process_name: "ezantivirusregistrationcheck.exe", Description: "e-trust antivirus"},
			{Process_name: "fprottray.exe", Description: "f-prot antivirus"},
			{Process_name: "fpwin.exe", Description: "verizon"},
			{Process_name: "freshclam.exe", Description: "clamav"},
			{Process_name: "fsbwsys.exe", Description: "f-secure"},
			{Process_name: "fsdfwd.exe", Description: "f-secure"},
			{Process_name: "fsgk32st.exe", Description: "f-secure"},
			{Process_name: "fssm32.exe", Description: "f-secure"},
			{Process_name: "guardgui.exe", Description: "网游保镖"},
			{Process_name: "guardnt.exe", Description: "ikarus"},
			{Process_name: "inocit.exe", Description: "etrust"},
			{Process_name: "inorpc.exe", Description: "etrust"},
			{Process_name: "inort.exe", Description: "etrust"},
			{Process_name: "inotask.exe", Description: "etrust"},
			{Process_name: "inouptng.exe", Description: "etrust"},
			{Process_name: "isafe.exe", Description: "etrust"},
			{Process_name: "kav.exe", Description: "kaspersky"},
			{Process_name: "kavmm.exe", Description: "kaspersky"},
			{Process_name: "kavpf.exe", Description: "kaspersky"},
			{Process_name: "kazza.exe", Description: "kaspersky"},
			{Process_name: "kavpfw.exe", Description: "kaspersky"},
			{Process_name: "kavstart.exe", Description: "kaspersky"},
			{Process_name: "kavsvc.exe", Description: "kaspersky"},
			{Process_name: "kavsvcui.exe", Description: "kaspersky"},
			{Process_name: "kmailmon.exe", Description: "金山毒霸"},
			{Process_name: "mcregwiz.exe", Description: "mcafee"},
			{Process_name: "minilog.exe", Description: "zone alarm"},
			{Process_name: "myagtsvc.exe", Description: "mcafee"},
			{Process_name: "myagttry.exe", Description: "mcafee"},
			{Process_name: "navlu32.exe", Description: "norton"},
			{Process_name: "neowatchlog.exe", Description: "neowatch"},
			{Process_name: "neowatchtray.exe", Description: "neowatch"},
			{Process_name: "nod32.exe", Description: "eset nod32"},
			{Process_name: "npfmsg.exe", Description: "norman个人防火墙"},
			{Process_name: "nsmdtr.exe", Description: "norton"},
			{Process_name: "ofcpfwsvc.exe", Description: "officescannt"},
			{Process_name: "op_mon.exe", Description: "outpostfirewall"},
			{Process_name: "pavfires.exe", Description: "熊猫卫士"},
			{Process_name: "pavfnsvr.exe", Description: "熊猫卫士"},
			{Process_name: "pavkre.exe", Description: "熊猫卫士"},
			{Process_name: "pavprot.exe", Description: "熊猫卫士"},
			{Process_name: "pavproxy.exe", Description: "熊猫卫士"},
			{Process_name: "pavprsrv.exe", Description: "熊猫卫士"},
			{Process_name: "pavsrv51.exe", Description: "熊猫卫士"},
			{Process_name: "pavss.exe", Description: "熊猫卫士"},
			{Process_name: "pccguide.exe", Description: "pc-cillin"},
			{Process_name: "pcciomon.exe", Description: "pc-cillin"},
			{Process_name: "pccntmon.exe", Description: "趋势科技 OfficeScan - 控制台"},
			{Process_name: "pccpfw.exe", Description: "趋势科技"},
			{Process_name: "pcctlcom.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "pctav.exe", Description: "pc tools antivirus"},
			{Process_name: "pestpatrol.exe", Description: "ikarus"},
			{Process_name: "prevsrv.exe", Description: "熊猫卫士"},
			{Process_name: "savadminservice.exe", Description: "sav"},
			{Process_name: "savmain.exe", Description: "sav"},
			{Process_name: "savscan.exe", Description: "sav"},
			{Process_name: "sdhelp.exe", Description: "spyware doctor"},
			{Process_name: "spidercpl.exe", Description: "dr.web"},
			{Process_name: "spiderml.exe", Description: "Dr.Web - 邮件扫描引擎"},
			{Process_name: "spiderui.exe", Description: "dr.web"},
			{Process_name: "spybotsd.exe", Description: "spybot"},
			{Process_name: "swagent.exe", Description: "sonicwall"},
			{Process_name: "swdoctor.exe", Description: "sonicwall"},
			{Process_name: "swnetsup.exe", Description: "sophos"},
			{Process_name: "symsport.exe", Description: "sysmantec"},
			{Process_name: "symwsc.exe", Description: "sysmantec"},
			{Process_name: "synmgr.exe", Description: "sysmantec"},
			{Process_name: "tmlisten.exe", Description: "趋势科技"},
			{Process_name: "tmntsrv.exe", Description: "趋势科技 - 实时监控服务"},
			{Process_name: "tmproxy.exe", Description: "趋势科技"},
			{Process_name: "tnbutil.exe", Description: "anti-virus"},
			{Process_name: "vcrmon.exe", Description: "viruschaser"},
			{Process_name: "vrmonnt.exe", Description: "hauri"},
			{Process_name: "vrmonsvc.exe", Description: "hauri"},
			{Process_name: "xcommsvr.exe", Description: "bitdefender"},
			{Process_name: "afwserv.exe", Description: "avast antivirus"},
			{Process_name: "ksafesvc.exe", Description: "金山毒霸"},
			{Process_name: "kwatch.exe", Description: "金山毒霸"},
			{Process_name: "scan32.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "aawtray.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "ad-aware.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "ackwin32.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "adaware.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "advxdwin.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "agentsvr.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "agentw.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "alevir.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "amon9x.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "antivirus.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "ants.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "apimonitor.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "aplica32.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "atcon.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "atro55en.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "atupdater.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "auto-protect.nav80try.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "autotrace.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "autoupdate.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "ave32.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "avp32.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "avpcc.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "avwin95.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "avwinnt.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "avwupd.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "avwupd32.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "avxmonitor9x.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "avxmonitornt.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "avxquar.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "backweb.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "bd_professional.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "belt.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "bidef.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "bidserver.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "bipcp.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "bipcpevalsetup.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "bisp.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "bootconf.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "borg2.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "bs120.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "bundle.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "bvt.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "ccpxysvc.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "cfiadmin.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "cfiaudit.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "cfinet.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "cfinet32.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "claw95.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "claw95cf.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "click.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "cmesys.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "cmgrdian.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "cmon016.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "connectionmonitor.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "cpf9x206.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "cpfnt206.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "ctrl.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "cv.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "cwnb181.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "cwntdwmo.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "datemanager.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "dcomx.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "deputy.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "divx.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "dllcache.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "dllreg.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "doors.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "dpf.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "dpfsetup.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "drwatson.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "drweb32.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "drwebupw.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "dvp95.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "dvp95_0.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "ecengine.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "efpeadm.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "ent.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "esafe.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "escanhnt.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "escanv95.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "espwatch.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "etrustcipe.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "evpn.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "exantivirus-cnet.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "exe.avxw.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "expert.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "explore.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "f-agnt95.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "f-prot95.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "f-stopw.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "fameh32.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "fp-win_trial.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "fprot.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "frw.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "gator.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "gbmenu.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "gbpoll.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "generics.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "gmt.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "hacktracersetup.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "hbinst.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "hbsrv.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "hotactio.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "hotpatch.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "htlog.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "hwpe.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "hxdl.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "hxiul.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "ibmasn.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "ibmavsp.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "icload95.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "icloadnt.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "icmon.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "icsupp95.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "icsuppnt.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "idle.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "iedll.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "ifw2000.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "inetlnfo.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "init.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "intren.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "iomon98.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "istsvc.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "jammer.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "jdbgmrg.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "jedi.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "kavlite40eng.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "kavpers40eng.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "kerio-pf-213-en-win.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "kerio-wrl-421-en-win.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "kerio-wrp-421-en-win.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "kernel32.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "killprocesssetup161.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "ldnetmon.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "ldpro.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "ldpromenu.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "lnetinfo.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "loader.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "localnet.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "lockdown.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "lockdown2000.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "lookout.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "lordpe.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "lsetup.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "luinit.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "luspt.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "mapisvc32.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "md.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "monitor.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "moolive.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "mrflux.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "msapp.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "msbb.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "msblast.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "msccn32.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "msconfig.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "msdm.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "msdos.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "msinfo32.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "mslaugh.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "msmsgri32.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "mssmmc32.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "mssys.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "mu0311ad.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "mwatch.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "n32scanw.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "navap.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "navdx.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "navnt.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "navstub.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "navwnt.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "nc2000.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "ncinst4.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "neomonitor.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "netarmor.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "netd32.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "netinfo.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "netmon.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "netscanpro.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "netspyhunter-1.2.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "netstat.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "netutils.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "normist.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "norton_internet_secu_3.0_407.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "notstart.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "npf40_tw_98_nt_me_2k.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "npfmessenger.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "nsched32.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "nssys32.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "nstask32.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "nsupdate.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "nt.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "ntvdm.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "ntxconfig.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "nui.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "nupgrade.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "nvarch16.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "nvc95.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "nvsvc32.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "nwinst4.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "nwservice.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "nwtool16.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "ollydbg.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "onsrvr.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "optimize.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "ostronet.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "otfix.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "outpostproinstall.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "padmin.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "panixk.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "pavcl.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "pavsched.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "pavw.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "pccwin98.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "pcfwallicon.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "pcip10117_0.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "pdsetup.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "periscope.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "perswf.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "pf2.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "pfwadmin.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "pingscan.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "platin.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "popscan.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "portdetective.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "portmonitor.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "ppinupdt.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "pptbc.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "ppvstop.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "procdump.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "procexplorerv1.0.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "programauditor.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "proport.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "pspf.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "purge.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "rav7.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "rav7win.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "rav8win32eng.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "ray.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "reged.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "regedit.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "regedt32.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "rescue.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "rrguard.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "rshell.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "rundll.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "rundll16.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "ruxdll32.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "sahagent.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "save.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "savenow.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "sc.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "scam32.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "scan95.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "scanpm.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "serv95.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "setup_flowprotector_us.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "setupvameeval.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "sgssfw32.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "shellspyinstall.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "shn.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "sms.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "smss32.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "sofi.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "sperm.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "spf.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "spoler.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "spoolcv.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "spoolsv32.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "spyxx.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "srng.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "ss3edit.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "ssg_4104.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "ssgrate.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "st2.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "start.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "stcloader.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "supftrl.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "support.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "svchosts.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "sweep95.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "sweepnet.sweepsrv.sys.swnetsup.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "sysedit.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "sysupd.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "taskmg.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "taskmo.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "taumon.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "tca.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "tcm.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "tds-3.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "tds2-98.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "tds2-nt.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "teekids.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "tfak.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "tfak5.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "tgbob.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "titaninxp.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "tracert.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "trickler.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "trjscan.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "trjsetup.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "trojantrap3.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "tsadbot.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "undoboot.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "updat.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "update.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "upgrad.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "utpost.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "vbcmserv.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "vbcons.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "vbust.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "vbwin9x.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "vbwinntw.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "vcsetup.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "vet32.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "vet95.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "vfsetup.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "vir-help.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "virusmdpersonalfirewall.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "vnlan300.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "vnpc3000.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "vpfw30s.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "vscan40.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "vscenu6.02d30.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "vsched.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "vsecomr.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "vsisetup.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "vswin9xe.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "vswinntse.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "vswinperse.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "w32dsm89.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "w9x.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "watchdog.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "webdav.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "webtrap.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "wfindv32.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "whoswatchingme.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "wimmun32.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "win-bugsfix.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "win32.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "win32us.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "winactive.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "window.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "windows.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "wininetd.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "wininitx.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "winlogin.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "winmain.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "winnet.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "winppr32.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "winrecon.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "winservn.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "winssk32.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "winstart.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "winstart001.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "wintsk32.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "winupdate.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "wkufind.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "wnad.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "wnt.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "wradmin.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "wrctrl.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "wsbgate.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "wupdater.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "wupdt.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "wyvernworksfirewall.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "xpf202en.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "zapsetup3001.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "zatutor.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "zonalm2601.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "akrnl.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "trojan.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "antivir.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "armor2net.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "ashenhcd.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "ashpopwz.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "ashskpck.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "aveval.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "avevl32.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "avgam.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "avgcc.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "avxmonitor.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "cafix.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "bitdefender.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "cfpconfig.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "drvirus.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "dwebllio.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "dwebio.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "escanh95.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "filemon.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "forticlient.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "fortiscan.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "fpavserver.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "f-sched.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "fspex.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "gcasdtserv.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "gcasserv.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "giantantispyware.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "guardxservice.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "guardxkickoff.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "hregmon.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "hrres.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "hsockpe.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "hupdate.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "icssuppnt.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "inetupd.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "isatray.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "mamutu.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "npavtray.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "nssserv.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "nsstray.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "ntos.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "nvcod.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "nvcte.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "nvcut.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "onlinent.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "opssvc.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "pertsk.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "pervac.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "pnmsrv.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "prevx.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "psimsvc.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "qhonline.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "qhonsvc.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "qhwscsvc.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "qhset.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "sality.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "sapissvc.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "scanwscs.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "scanningprocess.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "sdra64.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "sitecli.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "stopsignav.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "vba32ecm.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "vba32ifs.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "vba32ldr.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "vba32pp3.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "vbsntw.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "vrfwsvc.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "vrrw32.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "winssnotify.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "zlclient.exe", Description: "已知杀软进程,名称暂未收录"},
			{Process_name: "360tray.exe", Description: "360安全卫士-实时保护"},
			{Process_name: "360safe.exe", Description: "360安全卫士-主程序"},
			{Process_name: "ZhuDongFangYu.exe", Description: "360安全卫士-主动防御"},
			{Process_name: "360sd.exe", Description: "360杀毒"},
			{Process_name: "a2guard.exe", Description: "a-squared杀毒"},
			{Process_name: "ad-watch.exe", Description: "Lavasoft杀毒"},
			{Process_name: "cleaner8.exe", Description: "The Cleaner杀毒"},
			{Process_name: "vba32lder.exe", Description: "vb32杀毒"},
			{Process_name: "MongoosaGUI.exe", Description: "Mongoosa杀毒"},
			{Process_name: "CorantiControlCenter32.exe", Description: "Coranti2012杀毒"},
			{Process_name: "F-PROT.exe", Description: "F-Prot AntiVirus"},
			{Process_name: "CMCTrayIcon.exe", Description: "CMC杀毒"},
			{Process_name: "K7TSecurity.exe", Description: "K7杀毒"},
			{Process_name: "UnThreat.exe", Description: "UnThreat杀毒"},
			{Process_name: "CKSoftShiedAntivirus4.exe", Description: "Shield Antivirus杀毒"},
			{Process_name: "AVWatchService.exe", Description: "VIRUSfighter杀毒"},
			{Process_name: "ArcaTasksService.exe", Description: "ArcaVir杀毒"},
			{Process_name: "iptray.exe", Description: "Immunet杀毒"},
			{Process_name: "PSafeSysTray.exe", Description: "PSafe杀毒"},
			{Process_name: "nspupsvc.exe", Description: "nProtect杀毒"},
			{Process_name: "SpywareTerminatorShield.exe", Description: "SpywareTerminator反间谍软件"},
			{Process_name: "BKavService.exe", Description: "Bkav杀毒"},
			{Process_name: "MsMpEng.exe", Description: "Microsoft Security Essentials"},
			{Process_name: "SBAMSvc.exe", Description: "VIPRE"},
			{Process_name: "ccSvcHst.exe", Description: "Norton杀毒"},
			{Process_name: "f-secure.exe", Description: "冰岛"},
			{Process_name: "avp.exe", Description: "Kaspersky"},
			{Process_name: "KvMonXP.exe", Description: "江民杀毒"},
			{Process_name: "RavMonD.exe", Description: "瑞星杀毒"},
			{Process_name: "Mcshield.exe", Description: "McAfee"},
			{Process_name: "Tbmon.exe", Description: "McAfee"},
			{Process_name: "Frameworkservice.exe", Description: "McAfee"},
			{Process_name: "egui.exe", Description: "ESET NOD32"},
			{Process_name: "ekrn.exe", Description: "ESET NOD32"},
			{Process_name: "eguiProxy.exe", Description: "ESET NOD32"},
			{Process_name: "kxetray.exe", Description: "金山毒霸"},
			{Process_name: "knsdtray.exe", Description: "可牛杀毒"},
			{Process_name: "TMBMSRV.exe", Description: "趋势杀毒"},
			{Process_name: "avcenter.exe", Description: "Avira(小红伞)"},
			{Process_name: "avguard.exe", Description: "Avira(小红伞)"},
			{Process_name: "avgnt.exe", Description: "Avira(小红伞)"},
			{Process_name: "sched.exe", Description: "Avira(小红伞)"},
			{Process_name: "ashDisp.exe", Description: "Avast网络安全"},
			{Process_name: "rtvscan.exe", Description: "诺顿杀毒"},
			{Process_name: "ccapp.exe", Description: "SymantecNorton"},
			{Process_name: "NPFMntor.exe", Description: "Norton杀毒软件"},
			{Process_name: "ccSetMgr.exe", Description: "赛门铁克"},
			{Process_name: "ccRegVfy.exe", Description: "Norton杀毒软件"},
			{Process_name: "ksafe.exe", Description: "金山卫士"},
			{Process_name: "QQPCRTP.exe", Description: "QQ电脑管家"},
			{Process_name: "avgwdsvc.exe", Description: "AVG杀毒"},
			{Process_name: "QUHLPSVC.exe", Description: "QUICK HEAL杀毒"},
			{Process_name: "mssecess.exe", Description: "微软杀毒"},
			{Process_name: "HRService.exe", Description: "火绒安全软件 - 后台核心服务"},
			{Process_name: "HRUI.exe", Description: "火绒安全软件 - 主界面程序"},
			{Process_name: "qihuUpdate.exe", Description: "360安全产品 - 更新模块（奇虎360）"},
			{Process_name: "SevCenter.exe", Description: "安天智甲（Antiy）- 安全服务管理中心"},
			{Process_name: "AnVir.exe", Description: "AnVir Task Manager - 带防病毒功能的系统工具（国产）"},
			{Process_name: "yunsvc.exe", Description: "百度杀毒 - 云查杀服务"},
			{Process_name: "bdsvr.exe", Description: "百度杀毒 - 主进程"},
			{Process_name: "BaiduSdTray.exe", Description: "百度杀毒 - 托盘程序"},
			{Process_name: "QHWatchdog.exe", Description: "360安全卫士 - 看门狗进程"},
			{Process_name: "ESecCtrl.exe", Description: "企业级安全卫士 - 奇安信系列进程"},
			{Process_name: "TQTray.exe", Description: "奇安信天擎 - 奇安信系列进程"},
			{Process_name: "rsu.exe", Description: "瑞星杀毒软件 - 用户界面模块（Rising）"},
			{Process_name: "rstray.exe", Description: "瑞星杀毒软件 - 托盘程序（Rising）"},
			{Process_name: "avkproxy.exe", Description: "G Data Antivirus - Web防护代理（德国G Data）"},
			{Process_name: "avkwctl.exe", Description: "G Data Antivirus - 控制中心"},
			{Process_name: "trustport.exe", Description: "TrustPort Antivirus - 主程序（捷克TrustPort）"},
			{Process_name: "drweb32w.exe", Description: "Dr.Web Antivirus - 主程序（俄罗斯Doctor Web）"},
			{Process_name: "bdss.exe", Description: "BitDefender Antivirus - 安全服务（罗马尼亚Bitdefender）"},
			{Process_name: "vsserv.exe", Description: "BitDefender - 实时保护服务"},
			{Process_name: "bdagent.exe", Description: "BitDefender - 托盘程序"},
			{Process_name: "avgui.exe", Description: "AVG Antivirus - 用户界面"},
			{Process_name: "avastui.exe", Description: "Avast Antivirus - 图形界面程序"},
			{Process_name: "sbamtray.exe", Description: "VIPRE Antivirus - 托盘服务"},
			{Process_name: "zavaux.exe", Description: "ZoneAlarm Antivirus - 自动更新模块（Check Point）"},
			{Process_name: "zatray.exe", Description: "ZoneAlarm - 托盘程序"},
			{Process_name: "clamtray.exe", Description: "ClamWin Antivirus - 托盘程序（开源）"},
			{Process_name: "clamd.exe", Description: "ClamAV - 后台杀毒服务（开源）"},
			{Process_name: "twister.exe", Description: "Twister Antivirus - 主程序（Filseclab，中国）"},
			{Process_name: "nortonsecurity.exe", Description: "Norton Antivirus - 核心用户界面（Symantec）"},
			{Process_name: "cfp.exe", Description: "Comodo Firewall / Antivirus - 主程序"},
			{Process_name: "mbam.exe", Description: "Malwarebytes Anti-Malware - 用户界面"},
			{Process_name: "mbamservice.exe", Description: "Malwarebytes - 主服务"},
			{Process_name: "emsisoft.exe", Description: "Emsisoft Anti-Malware - 主进程"},
			{Process_name: "emsvc.exe", Description: "Emsisoft Anti-Malware - 后台服务"},
			{Process_name: "zillya.exe", Description: "Zillya! Antivirus - 乌克兰杀毒软件"},
			{Process_name: "maxsecure.exe", Description: "Max Secure Antivirus - 主进程"},
			{Process_name: "nanoav.exe", Description: "NANO Antivirus - 主界面（俄罗斯）"},
			{Process_name: "titanium.exe", Description: "趋势科技 Titanium - 主界面"},
		}
		if err := db.Create(&defaultSites).Error; err != nil {
			log.Fatalf("Error inserting default data: %v", err)
		}
	}
}
