// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGlobalProxy() {
  return window['go']['proxy']['ProxyManager']['GetGlobalProxy']();
}

export function GetHTTPClient() {
  return window['go']['proxy']['ProxyManager']['GetHTTPClient']();
}

export function GetProxyStatus() {
  return window['go']['proxy']['ProxyManager']['GetProxyStatus']();
}

export function SetCtx(arg1) {
  return window['go']['proxy']['ProxyManager']['SetCtx'](arg1);
}

export function SetGlobalProxy(arg1, arg2) {
  return window['go']['proxy']['ProxyManager']['SetGlobalProxy'](arg1, arg2);
}

export function TestProxyConnection(arg1) {
  return window['go']['proxy']['ProxyManager']['TestProxyConnection'](arg1);
}
