// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckDatasets() {
  return window['go']['proxy']['Proxy']['CheckDatasets']();
}

export function ChooseFile() {
  return window['go']['proxy']['Proxy']['ChooseFile']();
}

export function Debug(arg1) {
  return window['go']['proxy']['Proxy']['Debug'](arg1);
}

export function Error(arg1) {
  return window['go']['proxy']['Proxy']['Error'](arg1);
}

export function Fatal(arg1) {
  return window['go']['proxy']['Proxy']['Fatal'](arg1);
}

export function FetchProxies() {
  return window['go']['proxy']['Proxy']['FetchProxies']();
}

export function GetProfile() {
  return window['go']['proxy']['Proxy']['GetProfile']();
}

export function Info(arg1) {
  return window['go']['proxy']['Proxy']['Info'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['proxy']['Proxy']['SaveConfig'](arg1);
}

export function SetCtx(arg1) {
  return window['go']['proxy']['Proxy']['SetCtx'](arg1);
}

export function StopListening() {
  return window['go']['proxy']['Proxy']['StopListening']();
}

export function UseFetchedDatasets() {
  return window['go']['proxy']['Proxy']['UseFetchedDatasets']();
}

export function Warn(arg1) {
  return window['go']['proxy']['Proxy']['Warn'](arg1);
}
