// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {proxy} from '../models';
import {http} from '../models';
import {context} from '../models';

export function GetGlobalProxy():Promise<proxy.GlobalProxyResponse>;

export function GetHTTPClient():Promise<http.Client>;

export function GetProxyStatus():Promise<proxy.ProxyStatus>;

export function SetCtx(arg1:context.Context):Promise<void>;

export function SetGlobalProxy(arg1:proxy.ProxyConfig,arg2:boolean):Promise<boolean>;

export function TestProxyConnection(arg1:proxy.ProxyConfig):Promise<boolean>;
