// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gorm} from '../models';
import {system} from '../models';
import {controller} from '../models';
import {context} from '../models';

export function Db():Promise<gorm.DB>;

export function GetAppPath():Promise<string>;

export function InitMianSha():Promise<system.Base>;

export function Log(arg1:string):Promise<system.Base>;

export function QueryAntivirusProcesses(arg1:string):Promise<Array<Record<string, string>>>;

export function QueryGoogleQueries(arg1:string):Promise<Array<Record<string, any>>>;

export function QueryPasswords(arg1:number,arg2:number):Promise<Array<controller.PasswordData>>;

export function QueryPasswordsAPI(arg1:number,arg2:number,arg3:string):Promise<Record<string, any>>;

export function QueryPasswordsWithQuery(arg1:number,arg2:number,arg3:string):Promise<Array<controller.PasswordData>>;

export function Schema(arg1:Array<any>):Promise<void>;

export function SetCtx(arg1:context.Context):Promise<void>;
