// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Db() {
  return window['go']['controller']['Assistive']['Db']();
}

export function FscanResultDeal(arg1) {
  return window['go']['controller']['Assistive']['FscanResultDeal'](arg1);
}

export function FscanTextDeal(arg1) {
  return window['go']['controller']['Assistive']['FscanTextDeal'](arg1);
}

export function GetAppPath() {
  return window['go']['controller']['Assistive']['GetAppPath']();
}

export function InitMianSha() {
  return window['go']['controller']['Assistive']['InitMianSha']();
}

export function Log(arg1) {
  return window['go']['controller']['Assistive']['Log'](arg1);
}

export function QueryAntivirusProcesses(arg1) {
  return window['go']['controller']['Assistive']['QueryAntivirusProcesses'](arg1);
}

export function QueryGoogleQueries(arg1) {
  return window['go']['controller']['Assistive']['QueryGoogleQueries'](arg1);
}

export function QueryPasswords(arg1, arg2) {
  return window['go']['controller']['Assistive']['QueryPasswords'](arg1, arg2);
}

export function QueryPasswordsAPI(arg1, arg2, arg3) {
  return window['go']['controller']['Assistive']['QueryPasswordsAPI'](arg1, arg2, arg3);
}

export function QueryPasswordsWithQuery(arg1, arg2, arg3) {
  return window['go']['controller']['Assistive']['QueryPasswordsWithQuery'](arg1, arg2, arg3);
}

export function Schema(arg1) {
  return window['go']['controller']['Assistive']['Schema'](arg1);
}

export function SetCtx(arg1) {
  return window['go']['controller']['Assistive']['SetCtx'](arg1);
}

export function UploadFile(arg1, arg2) {
  return window['go']['controller']['Assistive']['UploadFile'](arg1, arg2);
}
