// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function IsVisible():Promise<boolean>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetHotkey(arg1:string):Promise<void>;

export function ToggleShowHide():Promise<void>;

export function UnregisterHotkey():Promise<void>;
