// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function IsVisible() {
  return window['go']['controller']['HotKey']['IsVisible']();
}

export function SetContext(arg1) {
  return window['go']['controller']['HotKey']['SetContext'](arg1);
}

export function SetHotkey(arg1) {
  return window['go']['controller']['HotKey']['SetHotkey'](arg1);
}

export function ToggleShowHide() {
  return window['go']['controller']['HotKey']['ToggleShowHide']();
}

export function UnregisterHotkey() {
  return window['go']['controller']['HotKey']['UnregisterHotkey']();
}
