// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DealOssList(arg1) {
  return window['go']['controller']['InfoDeal']['DealOssList'](arg1);
}

export function FscanResultDeal(arg1) {
  return window['go']['controller']['InfoDeal']['FscanResultDeal'](arg1);
}

export function GetExcelContent(arg1) {
  return window['go']['controller']['InfoDeal']['GetExcelContent'](arg1);
}

export function UploadFile(arg1, arg2) {
  return window['go']['controller']['InfoDeal']['UploadFile'](arg1, arg2);
}
