// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gorm} from '../models';
import {system} from '../models';
import {context} from '../models';

export function Db():Promise<gorm.DB>;

export function DealOssList(arg1:string):Promise<string>;

export function DetectCloudProvider(arg1:string):Promise<Record<string, any>>;

export function FscanResultDeal(arg1:string):Promise<string>;

export function GetAppPath():Promise<string>;

export function GetExcelContent(arg1:string):Promise<string>;

export function InitMianSha():Promise<system.Base>;

export function Log(arg1:string):Promise<system.Base>;

export function Schema(arg1:Array<any>):Promise<void>;

export function SetCtx(arg1:context.Context):Promise<void>;

export function StartVulnScan(arg1:string,arg2:string):Promise<Record<string, any>>;

export function UploadFile(arg1:string,arg2:string):Promise<void>;
