// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Db() {
  return window['go']['controller']['InfoDeal']['Db']();
}

export function DealOssList(arg1) {
  return window['go']['controller']['InfoDeal']['DealOssList'](arg1);
}

export function DetectCloudProvider(arg1) {
  return window['go']['controller']['InfoDeal']['DetectCloudProvider'](arg1);
}

export function FscanResultDeal(arg1) {
  return window['go']['controller']['InfoDeal']['FscanResultDeal'](arg1);
}

export function GetAppPath() {
  return window['go']['controller']['InfoDeal']['GetAppPath']();
}

export function GetExcelContent(arg1) {
  return window['go']['controller']['InfoDeal']['GetExcelContent'](arg1);
}

export function InitMianSha() {
  return window['go']['controller']['InfoDeal']['InitMianSha']();
}

export function Log(arg1) {
  return window['go']['controller']['InfoDeal']['Log'](arg1);
}

export function Schema(arg1) {
  return window['go']['controller']['InfoDeal']['Schema'](arg1);
}

export function SetCtx(arg1) {
  return window['go']['controller']['InfoDeal']['SetCtx'](arg1);
}

export function StartVulnScan(arg1, arg2) {
  return window['go']['controller']['InfoDeal']['StartVulnScan'](arg1, arg2);
}

export function UploadFile(arg1, arg2) {
  return window['go']['controller']['InfoDeal']['UploadFile'](arg1, arg2);
}
