// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {controller} from '../models';

export function QueryAntivirusProcesses(arg1:string):Promise<Array<{[key: string]: string}>>;

export function QueryGoogleQueries(arg1:string):Promise<Array<{[key: string]: any}>>;

export function QueryPasswords(arg1:number,arg2:number):Promise<Array<controller.PasswordData>>;

export function QueryPasswordsAPI(arg1:number,arg2:number,arg3:string):Promise<{[key: string]: any}>;

export function QueryPasswordsWithQuery(arg1:number,arg2:number,arg3:string):Promise<Array<controller.PasswordData>>;
