// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DealOssList(arg1:string):Promise<string>;

export function FscanResultDeal(arg1:string):Promise<string>;

export function GetExcelContent(arg1:string):Promise<string>;

export function UploadFile(arg1:string,arg2:string):Promise<void>;
