// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function QueryAntivirusProcesses(arg1) {
  return window['go']['controller']['InfoSearch']['QueryAntivirusProcesses'](arg1);
}

export function QueryGoogleQueries(arg1) {
  return window['go']['controller']['InfoSearch']['QueryGoogleQueries'](arg1);
}

export function QueryPasswords(arg1, arg2) {
  return window['go']['controller']['InfoSearch']['QueryPasswords'](arg1, arg2);
}

export function QueryPasswordsAPI(arg1, arg2, arg3) {
  return window['go']['controller']['InfoSearch']['QueryPasswordsAPI'](arg1, arg2, arg3);
}

export function QueryPasswordsWithQuery(arg1, arg2, arg3) {
  return window['go']['controller']['InfoSearch']['QueryPasswordsWithQuery'](arg1, arg2, arg3);
}
