// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BruteForceJWT(arg1, arg2, arg3) {
  return window['go']['controller']['JwtCrackController']['BruteForceJWT'](arg1, arg2, arg3);
}

export function ChooseJwtFile() {
  return window['go']['controller']['JwtCrackController']['ChooseJwtFile']();
}

export function DecodeJWTWithAlg(arg1, arg2, arg3) {
  return window['go']['controller']['JwtCrackController']['DecodeJWTWithAlg'](arg1, arg2, arg3);
}

export function EncodeJWTWithAlg(arg1, arg2, arg3) {
  return window['go']['controller']['JwtCrackController']['EncodeJWTWithAlg'](arg1, arg2, arg3);
}
