// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateFile(arg1, arg2) {
  return window['go']['controller']['Note']['CreateFile'](arg1, arg2);
}

export function CreateFolder(arg1, arg2) {
  return window['go']['controller']['Note']['CreateFolder'](arg1, arg2);
}

export function Db() {
  return window['go']['controller']['Note']['Db']();
}

export function DeleteItem(arg1) {
  return window['go']['controller']['Note']['DeleteItem'](arg1);
}

export function GetAppPath() {
  return window['go']['controller']['Note']['GetAppPath']();
}

export function GetFiles(arg1) {
  return window['go']['controller']['Note']['GetFiles'](arg1);
}

export function GetNotesDir() {
  return window['go']['controller']['Note']['GetNotesDir']();
}

export function InitMianSha() {
  return window['go']['controller']['Note']['InitMianSha']();
}

export function Log(arg1) {
  return window['go']['controller']['Note']['Log'](arg1);
}

export function OpenDirectory() {
  return window['go']['controller']['Note']['OpenDirectory']();
}

export function ReadFile(arg1) {
  return window['go']['controller']['Note']['ReadFile'](arg1);
}

export function RenameItem(arg1, arg2) {
  return window['go']['controller']['Note']['RenameItem'](arg1, arg2);
}

export function SaveFile(arg1, arg2) {
  return window['go']['controller']['Note']['SaveFile'](arg1, arg2);
}

export function SaveImage(arg1, arg2) {
  return window['go']['controller']['Note']['SaveImage'](arg1, arg2);
}

export function Schema(arg1) {
  return window['go']['controller']['Note']['Schema'](arg1);
}

export function SetCtx(arg1) {
  return window['go']['controller']['Note']['SetCtx'](arg1);
}

export function Shutdown() {
  return window['go']['controller']['Note']['Shutdown']();
}

export function WatchDirectory(arg1) {
  return window['go']['controller']['Note']['WatchDirectory'](arg1);
}
