// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gorm} from '../models';
import {controller} from '../models';
import {system} from '../models';
import {context} from '../models';

export function CreateFile(arg1:string,arg2:string):Promise<void>;

export function CreateFolder(arg1:string,arg2:string):Promise<void>;

export function Db():Promise<gorm.DB>;

export function DeleteItem(arg1:string):Promise<void>;

export function GetAppPath():Promise<string>;

export function GetFiles(arg1:string):Promise<Array<controller.FileInfo>>;

export function GetNotesDir():Promise<string>;

export function InitMianSha():Promise<system.Base>;

export function Log(arg1:string):Promise<system.Base>;

export function OpenDirectory():Promise<string>;

export function ReadFile(arg1:string):Promise<string>;

export function RenameItem(arg1:string,arg2:string):Promise<void>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SaveImage(arg1:string,arg2:string):Promise<string>;

export function Schema(arg1:Array<any>):Promise<void>;

export function SetCtx(arg1:context.Context):Promise<void>;

export function Shutdown():Promise<void>;

export function WatchDirectory(arg1:string):Promise<void>;
