// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Db() {
  return window['go']['controller']['Server']['Db']();
}

export function GetAppPath() {
  return window['go']['controller']['Server']['GetAppPath']();
}

export function InitMianSha() {
  return window['go']['controller']['Server']['InitMianSha']();
}

export function Log(arg1) {
  return window['go']['controller']['Server']['Log'](arg1);
}

export function Schema(arg1) {
  return window['go']['controller']['Server']['Schema'](arg1);
}

export function SetCtx(arg1) {
  return window['go']['controller']['Server']['SetCtx'](arg1);
}
