// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckUseNums() {
  return window['go']['controller']['ShellConfig']['CheckUseNums']();
}

export function GetMachineCode() {
  return window['go']['controller']['ShellConfig']['GetMachineCode']();
}

export function IsInit() {
  return window['go']['controller']['ShellConfig']['IsInit']();
}

export function UpdateShellConfig() {
  return window['go']['controller']['ShellConfig']['UpdateShellConfig']();
}

export function VerifyAuth(arg1, arg2) {
  return window['go']['controller']['ShellConfig']['VerifyAuth'](arg1, arg2);
}
