// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckUseNums():Promise<boolean>;

export function GetMachineCode():Promise<string>;

export function IsInit():Promise<boolean>;

export function UpdateShellConfig():Promise<void>;

export function VerifyAuth(arg1:string,arg2:string):Promise<boolean>;
