// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {controller} from '../models';
import {gorm} from '../models';
import {system} from '../models';
import {context} from '../models';

export function AddSite(arg1:controller.SiteItem):Promise<number>;

export function Db():Promise<gorm.DB>;

export function DeleteSite(arg1:number):Promise<void>;

export function DeleteSiteCategory(arg1:string):Promise<void>;

export function FetchSiteInfo(arg1:string):Promise<Record<string, string>>;

export function GetAllSites():Promise<Array<controller.SiteCategory>>;

export function GetAppPath():Promise<string>;

export function GetCategoryList():Promise<Array<Record<string, any>>>;

export function GetSearchSites(arg1:string):Promise<Array<controller.SiteCategory>>;

export function InitMianSha():Promise<system.Base>;

export function Log(arg1:string):Promise<system.Base>;

export function MoveCommandToCategory(arg1:Record<string, any>):Promise<void>;

export function Schema(arg1:Array<any>):Promise<void>;

export function SetCtx(arg1:context.Context):Promise<void>;

export function UpdateCategorySorts(arg1:Array<Record<string, any>>):Promise<void>;

export function UpdateCommandSorts(arg1:Array<Record<string, any>>):Promise<void>;

export function UpdateSite(arg1:number,arg2:controller.SiteItem):Promise<void>;

export function UpdateSiteCategory(arg1:string,arg2:string):Promise<void>;
