// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {controller} from '../models';

export function AddSite(arg1:controller.SiteItem):Promise<number>;

export function DeleteSite(arg1:number):Promise<void>;

export function DeleteSiteCategory(arg1:string):Promise<void>;

export function GetAllSites():Promise<Array<controller.SiteCategory>>;

export function GetCategoryList():Promise<Array<{[key: string]: any}>>;

export function GetSearchSites(arg1:string):Promise<Array<controller.SiteCategory>>;

export function MoveCommandToCategory(arg1:{[key: string]: any}):Promise<void>;

export function UpdateCategorySorts(arg1:Array<{[key: string]: any}>):Promise<void>;

export function UpdateCommandSorts(arg1:Array<{[key: string]: any}>):Promise<void>;

export function UpdateSite(arg1:number,arg2:controller.SiteItem):Promise<void>;

export function UpdateSiteCategory(arg1:string,arg2:string):Promise<void>;
