// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSite(arg1) {
  return window['go']['controller']['Site']['AddSite'](arg1);
}

export function Db() {
  return window['go']['controller']['Site']['Db']();
}

export function DeleteSite(arg1) {
  return window['go']['controller']['Site']['DeleteSite'](arg1);
}

export function DeleteSiteCategory(arg1) {
  return window['go']['controller']['Site']['DeleteSiteCategory'](arg1);
}

export function FetchSiteInfo(arg1) {
  return window['go']['controller']['Site']['FetchSiteInfo'](arg1);
}

export function GetAllSites() {
  return window['go']['controller']['Site']['GetAllSites']();
}

export function GetAppPath() {
  return window['go']['controller']['Site']['GetAppPath']();
}

export function GetCategoryList() {
  return window['go']['controller']['Site']['GetCategoryList']();
}

export function GetSearchSites(arg1) {
  return window['go']['controller']['Site']['GetSearchSites'](arg1);
}

export function InitMianSha() {
  return window['go']['controller']['Site']['InitMianSha']();
}

export function Log(arg1) {
  return window['go']['controller']['Site']['Log'](arg1);
}

export function MoveCommandToCategory(arg1) {
  return window['go']['controller']['Site']['MoveCommandToCategory'](arg1);
}

export function Schema(arg1) {
  return window['go']['controller']['Site']['Schema'](arg1);
}

export function SetCtx(arg1) {
  return window['go']['controller']['Site']['SetCtx'](arg1);
}

export function UpdateCategorySorts(arg1) {
  return window['go']['controller']['Site']['UpdateCategorySorts'](arg1);
}

export function UpdateCommandSorts(arg1) {
  return window['go']['controller']['Site']['UpdateCommandSorts'](arg1);
}

export function UpdateSite(arg1, arg2) {
  return window['go']['controller']['Site']['UpdateSite'](arg1, arg2);
}

export function UpdateSiteCategory(arg1, arg2) {
  return window['go']['controller']['Site']['UpdateSiteCategory'](arg1, arg2);
}
