// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowserOpenURL(arg1) {
  return window['go']['controller']['System']['BrowserOpenURL'](arg1);
}

export function ClipboardGetText() {
  return window['go']['controller']['System']['ClipboardGetText']();
}

export function ClipboardSetText(arg1) {
  return window['go']['controller']['System']['ClipboardSetText'](arg1);
}

export function ExitApp() {
  return window['go']['controller']['System']['ExitApp']();
}

export function GetAutoStart() {
  return window['go']['controller']['System']['GetAutoStart']();
}

export function GetCPUUsage() {
  return window['go']['controller']['System']['GetCPUUsage']();
}

export function GetConfigDir() {
  return window['go']['controller']['System']['GetConfigDir']();
}

export function GetMemUsageSelf() {
  return window['go']['controller']['System']['GetMemUsageSelf']();
}

export function GetMemUsageTotal() {
  return window['go']['controller']['System']['GetMemUsageTotal']();
}

export function GetOpenChooseFilePath(arg1) {
  return window['go']['controller']['System']['GetOpenChooseFilePath'](arg1);
}

export function GetOpenDir() {
  return window['go']['controller']['System']['GetOpenDir']();
}

export function GetOpenFilePath() {
  return window['go']['controller']['System']['GetOpenFilePath']();
}

export function GetOs() {
  return window['go']['controller']['System']['GetOs']();
}

export function OpenConfigDir() {
  return window['go']['controller']['System']['OpenConfigDir']();
}

export function OpenPath(arg1) {
  return window['go']['controller']['System']['OpenPath'](arg1);
}

export function SetAutoStart(arg1) {
  return window['go']['controller']['System']['SetAutoStart'](arg1);
}

export function ShellCMD(arg1, arg2, arg3, arg4) {
  return window['go']['controller']['System']['ShellCMD'](arg1, arg2, arg3, arg4);
}
