// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowserOpenURL(arg1:string):Promise<void>;

export function ClipboardGetText():Promise<string>;

export function ClipboardSetText(arg1:string):Promise<void>;

export function GetOpenDir():Promise<string>;

export function GetOpenFilePath():Promise<string>;

export function GetOs():Promise<string>;

export function OpenConfigDir():Promise<void>;

export function OpenPath(arg1:string):Promise<void>;

export function ShellCMD(arg1:string,arg2:string,arg3:number):Promise<void>;
