// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelExit() {
  return window['go']['controller']['SystemTp']['CancelExit']();
}

export function ConfirmExit() {
  return window['go']['controller']['SystemTp']['ConfirmExit']();
}

export function Startup(arg1, arg2) {
  return window['go']['controller']['SystemTp']['Startup'](arg1, arg2);
}
