// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function CancelExit():Promise<void>;

export function ConfirmExit():Promise<void>;

export function Startup(arg1:context.Context,arg2:Array<number>):Promise<void>;
