// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {controller} from '../models';

export function AddTool(arg1:controller.ToolsItem):Promise<number>;

export function DeleteTool(arg1:number):Promise<void>;

export function DeleteToolCategory(arg1:string):Promise<void>;

export function GetAllTools():Promise<Array<controller.ToolsCategory>>;

export function GetCategoryList():Promise<Array<Record<string, any>>>;

export function GetSearchTools(arg1:string):Promise<Array<controller.ToolsCategory>>;

export function MoveCommandToCategory(arg1:Record<string, any>):Promise<void>;

export function UpdateCategorySorts(arg1:Array<Record<string, any>>):Promise<void>;

export function UpdateCommandSorts(arg1:Array<Record<string, any>>):Promise<void>;

export function UpdateTool(arg1:number,arg2:controller.ToolsItem):Promise<void>;

export function UpdateToolCategory(arg1:string,arg2:string):Promise<void>;
