// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTool(arg1) {
  return window['go']['controller']['Tool']['AddTool'](arg1);
}

export function DeleteTool(arg1) {
  return window['go']['controller']['Tool']['DeleteTool'](arg1);
}

export function DeleteToolCategory(arg1) {
  return window['go']['controller']['Tool']['DeleteToolCategory'](arg1);
}

export function GetAllTools() {
  return window['go']['controller']['Tool']['GetAllTools']();
}

export function GetCategoryList() {
  return window['go']['controller']['Tool']['GetCategoryList']();
}

export function GetSearchTools(arg1) {
  return window['go']['controller']['Tool']['GetSearchTools'](arg1);
}

export function MoveCommandToCategory(arg1) {
  return window['go']['controller']['Tool']['MoveCommandToCategory'](arg1);
}

export function ReadImageAsBase64(arg1) {
  return window['go']['controller']['Tool']['ReadImageAsBase64'](arg1);
}

export function UpdateCategorySorts(arg1) {
  return window['go']['controller']['Tool']['UpdateCategorySorts'](arg1);
}

export function UpdateCommandSorts(arg1) {
  return window['go']['controller']['Tool']['UpdateCommandSorts'](arg1);
}

export function UpdateTool(arg1, arg2) {
  return window['go']['controller']['Tool']['UpdateTool'](arg1, arg2);
}

export function UpdateToolCategory(arg1, arg2) {
  return window['go']['controller']['Tool']['UpdateToolCategory'](arg1, arg2);
}
