// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {controller} from '../models';

export function AutoDecompile(arg1:boolean):Promise<void>;

export function CheckDecompileStatus(arg1:string,arg2:string):Promise<string>;

export function ClearApplet():Promise<void>;

export function ClearDecompiled():Promise<void>;

export function Decompile(arg1:controller.InfoToFront):Promise<void>;

export function ExtractSensitiveInfo(arg1:string,arg2:string):Promise<void>;

export function GetAllMiniApp():Promise<Array<controller.InfoToFront>>;

export function GetAppletPath():Promise<string>;

export function GetMatchedString(arg1:string,arg2:string):Promise<Array<string>>;

export function GetWechatRules():Promise<Array<string>>;

export function InitCheck():Promise<boolean>;

export function SaveWechatRules(arg1:Array<string>):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SetAppletPath(arg1:string):Promise<void>;
