// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoDecompile(arg1) {
  return window['go']['controller']['UnWxapp']['AutoDecompile'](arg1);
}

export function CheckDecompileStatus(arg1, arg2) {
  return window['go']['controller']['UnWxapp']['CheckDecompileStatus'](arg1, arg2);
}

export function ClearApplet() {
  return window['go']['controller']['UnWxapp']['ClearApplet']();
}

export function ClearDecompiled() {
  return window['go']['controller']['UnWxapp']['ClearDecompiled']();
}

export function Decompile(arg1) {
  return window['go']['controller']['UnWxapp']['Decompile'](arg1);
}

export function ExtractSensitiveInfo(arg1, arg2) {
  return window['go']['controller']['UnWxapp']['ExtractSensitiveInfo'](arg1, arg2);
}

export function GetAllMiniApp() {
  return window['go']['controller']['UnWxapp']['GetAllMiniApp']();
}

export function GetAppletPath() {
  return window['go']['controller']['UnWxapp']['GetAppletPath']();
}

export function GetMatchedString(arg1, arg2) {
  return window['go']['controller']['UnWxapp']['GetMatchedString'](arg1, arg2);
}

export function GetWechatRules() {
  return window['go']['controller']['UnWxapp']['GetWechatRules']();
}

export function InitCheck() {
  return window['go']['controller']['UnWxapp']['InitCheck']();
}

export function SaveWechatRules(arg1) {
  return window['go']['controller']['UnWxapp']['SaveWechatRules'](arg1);
}

export function SelectDirectory() {
  return window['go']['controller']['UnWxapp']['SelectDirectory']();
}

export function SetAppletPath(arg1) {
  return window['go']['controller']['UnWxapp']['SetAppletPath'](arg1);
}
