// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenFolder(arg1) {
  return window['go']['controller']['UnWxapp']['OpenFolder'](arg1);
}

export function RunUnWxapp(arg1, arg2, arg3, arg4) {
  return window['go']['controller']['UnWxapp']['RunUnWxapp'](arg1, arg2, arg3, arg4);
}

export function SelectDirectory() {
  return window['go']['controller']['UnWxapp']['SelectDirectory']();
}
