// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {controller} from '../models';

export function OpenFolder(arg1:controller.OpenFolderRequest):Promise<void>;

export function RunUnWxapp(arg1:any,arg2:Array<string>,arg3:string,arg4:boolean):Promise<string>;

export function SelectDirectory():Promise<string>;
