// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Db() {
  return window['go']['controller']['User']['Db']();
}

export function GetAppPath() {
  return window['go']['controller']['User']['GetAppPath']();
}

export function InitMianSha() {
  return window['go']['controller']['User']['InitMianSha']();
}

export function Log(arg1) {
  return window['go']['controller']['User']['Log'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['controller']['User']['Login'](arg1, arg2);
}

export function Schema(arg1) {
  return window['go']['controller']['User']['Schema'](arg1);
}

export function SetCtx(arg1) {
  return window['go']['controller']['User']['SetCtx'](arg1);
}

export function UpdateUser(arg1, arg2) {
  return window['go']['controller']['User']['UpdateUser'](arg1, arg2);
}
