// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {controller} from '../models';

export function Login(arg1:string,arg2:string):Promise<void>;

export function UpdateUser(arg1:string,arg2:controller.UpdateUserItem):Promise<void>;
