// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectionCreate(arg1) {
  return window['go']['redis']['Redis']['ConnectionCreate'](arg1);
}

export function ConnectionDelete(arg1) {
  return window['go']['redis']['Redis']['ConnectionDelete'](arg1);
}

export function ConnectionEdit(arg1) {
  return window['go']['redis']['Redis']['ConnectionEdit'](arg1);
}

export function ConnectionList() {
  return window['go']['redis']['Redis']['ConnectionList']();
}

export function ConnectionTest(arg1) {
  return window['go']['redis']['Redis']['ConnectionTest'](arg1);
}

export function CreateKeyValue(arg1) {
  return window['go']['redis']['Redis']['CreateKeyValue'](arg1);
}

export function DbInfo(arg1) {
  return window['go']['redis']['Redis']['DbInfo'](arg1);
}

export function DbList(arg1) {
  return window['go']['redis']['Redis']['DbList'](arg1);
}

export function DeleteKeyValue(arg1) {
  return window['go']['redis']['Redis']['DeleteKeyValue'](arg1);
}

export function ExecuteCommand(arg1, arg2) {
  return window['go']['redis']['Redis']['ExecuteCommand'](arg1, arg2);
}

export function GetCommandHistory(arg1) {
  return window['go']['redis']['Redis']['GetCommandHistory'](arg1);
}

export function GetKeyValue(arg1) {
  return window['go']['redis']['Redis']['GetKeyValue'](arg1);
}

export function HashAddOrUpdateField(arg1) {
  return window['go']['redis']['Redis']['HashAddOrUpdateField'](arg1);
}

export function HashFieldDelete(arg1) {
  return window['go']['redis']['Redis']['HashFieldDelete'](arg1);
}

export function KeyList(arg1) {
  return window['go']['redis']['Redis']['KeyList'](arg1);
}

export function ListValueCreate(arg1) {
  return window['go']['redis']['Redis']['ListValueCreate'](arg1);
}

export function ListValueDelete(arg1) {
  return window['go']['redis']['Redis']['ListValueDelete'](arg1);
}

export function SetCtx(arg1) {
  return window['go']['redis']['Redis']['SetCtx'](arg1);
}

export function SetValueCreate(arg1) {
  return window['go']['redis']['Redis']['SetValueCreate'](arg1);
}

export function SetValueDelete(arg1) {
  return window['go']['redis']['Redis']['SetValueDelete'](arg1);
}

export function UpdateKeyValue(arg1) {
  return window['go']['redis']['Redis']['UpdateKeyValue'](arg1);
}

export function ZSetValueCreate(arg1) {
  return window['go']['redis']['Redis']['ZSetValueCreate'](arg1);
}

export function ZSetValueDelete(arg1) {
  return window['go']['redis']['Redis']['ZSetValueDelete'](arg1);
}
