// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {infoDeal} from '../models';
import {gorm} from '../models';
import {system} from '../models';
import {context} from '../models';

export function BruteForceJWT(arg1:string,arg2:string,arg3:string):Promise<infoDeal.JwtResult>;

export function ChooseJwtFile():Promise<string>;

export function Db():Promise<gorm.DB>;

export function DecodeJWTWithAlg(arg1:string,arg2:string,arg3:string):Promise<infoDeal.JwtResult>;

export function EncodeJWTWithAlg(arg1:string,arg2:string,arg3:Record<string, any>):Promise<infoDeal.JwtResult>;

export function GetAppPath():Promise<string>;

export function GetDefaultDictPath():Promise<string>;

export function InitMianSha():Promise<system.Base>;

export function Log(arg1:string):Promise<system.Base>;

export function Schema(arg1:Array<any>):Promise<void>;

export function SetCtx(arg1:context.Context):Promise<void>;
