// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Db() {
  return window['go']['infoDeal']['OssBucker']['Db']();
}

export function DealOssList(arg1) {
  return window['go']['infoDeal']['OssBucker']['DealOssList'](arg1);
}

export function DetectCloudProvider(arg1) {
  return window['go']['infoDeal']['OssBucker']['DetectCloudProvider'](arg1);
}

export function GetAppPath() {
  return window['go']['infoDeal']['OssBucker']['GetAppPath']();
}

export function InitMianSha() {
  return window['go']['infoDeal']['OssBucker']['InitMianSha']();
}

export function Log(arg1) {
  return window['go']['infoDeal']['OssBucker']['Log'](arg1);
}

export function Schema(arg1) {
  return window['go']['infoDeal']['OssBucker']['Schema'](arg1);
}

export function SetCtx(arg1) {
  return window['go']['infoDeal']['OssBucker']['SetCtx'](arg1);
}

export function StartVulnScan(arg1, arg2) {
  return window['go']['infoDeal']['OssBucker']['StartVulnScan'](arg1, arg2);
}
