// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchQueryIPLocation(arg1, arg2) {
  return window['go']['infoDeal']['QueryIp']['BatchQueryIPLocation'](arg1, arg2);
}

export function BatchQueryIPLocationWithProgress(arg1, arg2, arg3) {
  return window['go']['infoDeal']['QueryIp']['BatchQueryIPLocationWithProgress'](arg1, arg2, arg3);
}

export function Db() {
  return window['go']['infoDeal']['QueryIp']['Db']();
}

export function ExportIPResults(arg1) {
  return window['go']['infoDeal']['QueryIp']['ExportIPResults'](arg1);
}

export function GetAppPath() {
  return window['go']['infoDeal']['QueryIp']['GetAppPath']();
}

export function InitMianSha() {
  return window['go']['infoDeal']['QueryIp']['InitMianSha']();
}

export function Log(arg1) {
  return window['go']['infoDeal']['QueryIp']['Log'](arg1);
}

export function QueryIPLocation(arg1) {
  return window['go']['infoDeal']['QueryIp']['QueryIPLocation'](arg1);
}

export function Schema(arg1) {
  return window['go']['infoDeal']['QueryIp']['Schema'](arg1);
}

export function SetCtx(arg1) {
  return window['go']['infoDeal']['QueryIp']['SetCtx'](arg1);
}
