// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {infoDeal} from '../models';
import {gorm} from '../models';
import {system} from '../models';
import {context} from '../models';

export function BatchQueryIPLocation(arg1:infoDeal.IPQueryRequest,arg2:infoDeal.BatchQueryConfig):Promise<Array<infoDeal.IPQueryResponse>>;

export function BatchQueryIPLocationWithProgress(arg1:infoDeal.IPQueryRequest,arg2:infoDeal.BatchQueryConfig,arg3:any):Promise<Array<infoDeal.IPQueryResponse>>;

export function Db():Promise<gorm.DB>;

export function ExportIPResults(arg1:infoDeal.IPExportRequest):Promise<Record<string, any>>;

export function GetAppPath():Promise<string>;

export function InitMianSha():Promise<system.Base>;

export function Log(arg1:string):Promise<system.Base>;

export function QueryIPLocation(arg1:infoDeal.IPQueryRequest):Promise<infoDeal.IPQueryResponse>;

export function Schema(arg1:Array<any>):Promise<void>;

export function SetCtx(arg1:context.Context):Promise<void>;
