package request

import (
	"EasyTools/app/controller/proxy"
	"EasyTools/app/controller/proxy/config"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"strconv"
	"strings"
	"time"
)

type FofaAutoGenerated struct {
	Mode    string     `json:"mode"`
	Error   bool       `json:"error"`
	Query   string     `json:"query"`
	Page    int        `json:"page"`
	Size    int        `json:"size"`
	Results [][]string `json:"results"`
}

func fofa_api(keyword string, email string, key string, page int, size int) string {
	input := []byte(keyword)
	encodeString := base64.StdEncoding.EncodeToString(input)
	api_request := fmt.Sprintf("https://fofa.info/api/v1/search/all?email=%s&page=%d&size=%d&key=%s&qbase64=%s&fields=ip,host,title,port,protocol", strings.Trim(email, " "), page, size, strings.Trim(key, " "), encodeString)
	return api_request
}

func fofahttp(url string, timeout string) (*FofaAutoGenerated, error) {
	var itime, err = strconv.Atoi(timeout)
	if err != nil {
		log.Println("fofa超时参数错误: ", err)
	}
	client := proxy.GlobalProxyManager.GetHTTPClient()
	client = &http.Client{
		Timeout:   time.Duration(itime) * time.Second,
		Transport: client.Transport,
	}
	req, err := http.NewRequest("GET", url, nil)
	if err != nil {
		log.Println("创建请求失败:", err)
		return nil, fmt.Errorf("创建请求失败: %v", err)
	}
	req.Header.Set("Accept", "*/*;q=0.8")
	req.Header.Set("Connection", "close")
	req.Header.Set("User-Agent", "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.0 Safari/537.36")
	resp, err := client.Do(req)
	if err != nil {
		log.Println("HTTP请求失败:", err)
		return nil, fmt.Errorf("HTTP请求失败: %v", err)
	}
	defer resp.Body.Close()
	result, _ := io.ReadAll(resp.Body)
	res := &FofaAutoGenerated{}
	json.Unmarshal(result, &res)
	return res, nil
}

func Fafaall(keyword string) (urls []string, err error) {
	fofa := config.GetConfig()
	url := fofa_api(keyword, fofa.Email, fofa.FofaKey, 1, 100)
	res, err := fofahttp(url, fofa.Timeout)
	if err != nil {
		return nil, fmt.Errorf("fofa 第一页请求失败: %v", err)
	}
	pagelength := res.Size/1000 + 1
	for _, value := range res.Results {
		urls = append(urls, value[1])
	}
	Maxpage, _ := strconv.Atoi(fofa.Maxpage)
	if pagelength > 1 {
		for i := 2; i <= pagelength && i <= Maxpage; i++ {
			fmt.Println("fofa 正在请求第" + strconv.Itoa(i) + "页数据")
			url = fofa_api(keyword, fofa.Email, fofa.FofaKey, i, 100)
			res, _ = fofahttp(url, fofa.Timeout)
			if len(res.Results) > 0 {
				for _, value := range res.Results {
					urls = append(urls, value[1])
				}
			}
		}
	}

	return urls, nil
}

type FofaConfig struct {
}

func (fp *FofaConfig) Name() string {
	return "Fofa"
}

func (fp *FofaConfig) Fetch() ([]string, error) {
	fofa := config.GetConfig()

	var fofakeys string

	if fofa.FofaKey != "" && fofa.Email != "" {
		if fofa.Xui == "1" {
			fofakeys = "\"HttpUtil.post('/getTwoFactorEnable')\""
		} else {
			switch fofa.Country {
			case "0":
				fofakeys = "protocol==\"socks5\"&&protocol.banner=\"Method: 0x00 (No authentication)\""
			case "1":
				fofakeys = "protocol==\"socks5\"&&protocol.banner=\"Method: 0x00 (No authentication)\" && ip.country=\"CN\""
			case "2":
				fofakeys = "protocol==\"socks5\"&&protocol.banner=\"Method: 0x00 (No authentication)\" && ip.country!=\"CN\""
			}
		}

		urls, err := Fafaall(fofakeys)
		if err != nil {
			log.Printf("fofa搜索失败: %v", err)
			// 可以选择返回部分结果，或者返回错误
			return urls, err // 或者 return urls, nil 取决于你的需求
		}
		return urls, nil
	} else {
		return nil, nil
	}
}
